/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package list;
import java.util.*;

public class App {
<<<<<<< HEAD
	public static void main(String[] args) {
		List array1 = new List();
		Scanner input = new Scanner(System.in);
		int choice;	
		System.out.println("Initialized an Array");
		boolean exit = false;
		while (!exit) {

			System.out.println("1. Add");
			System.out.println("2. Get");
			System.out.println("3. Remove");
			System.out.print("Enter your option: ");
			choice = input.nextInt();
			int number;
			switch (choice) {
				case 1:
				System.out.print("Enter an element: ");
				number = input.nextInt();
				array1.add(number);
				break;

				case 2:
				System.out.print("Enter the index of element you want: ");
				number = input.nextInt();
				System.out.println(array1.get(number));
				break;

				case 3:
				System.out.print("Enter the element you want to remove: ");
				number = input.nextInt();
				array1.remove(number);
				break;

				default:
				exit = true;
				break;
			}
			System.out.println(Arrays.toString(array1.arr));

		}

		input.close();
	}
=======
    public static void main(String[] args) {
			List array1 = new List();
			array1.add(10);

		System.out.println(Arrays.toString(array1.arr));
			
    }
>>>>>>> 17e1d7825c85569685df2d5e3745b14e788200ff
}
