/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package list;
import java.util.*;

public class App {
    public static void main(String[] args) {
			List array1 = new List();
			array1.add(10);

		System.out.println(Arrays.toString(array1.arr));
			
    }
}
