/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package act1;
import java.util.*;
public class App {
    public static void main(String[] args) {
			Scanner sc = new Scanner(System.in);
			int a = sc.nextInt();
			int b = sc.nextInt();
			sc.close();
    }
}
